### PR TITLE
Image augmentation - Now we have 1601 photos!

### PR DESCRIPTION
**Pull request by Mars-98**
Just completed the image augmentation code. I have divided original dataset into 4 folders and augmented each folders' photos differently. I have combined the augmented result into one folder. I have then combined original and augmented into one folder as well. It seems like when I upload them onto github, since there are more than 1000 photos in some of the folders, github omits those pictures. Not sure if that means deleting the photos completely from github and that you wouldn't be able to view them when the repo is pulled or what. I will share final dataset with Connor, Leon, and Tim.

### CODE REVIEW

**Comment by coughenberg** [comment]
Get rid of all images in this pr plz

**Review by coughenberg — CHANGES_REQUESTED** [review]
Everything looks good, just put a link to the Jira story you are referencing with this in the description and I'll approve. This change request is per https://github.com/ARC-Summer-2020/AutoRockClimber/wiki/Pull-Review-Expectations

Also make sure the Jira story is labelled as 'review', because it is in review

**Comment by Mars-98** [comment]
Oh my bad, 
https://tim-kaufenberg.atlassian.net/browse/ARC-36

**Review by coughenberg — APPROVED** [review]

**Comment by coughenberg** [comment]
Whoever approves next please squash and merge

**Review by skitscha — APPROVED** [review]

**Pull request merged**
