### PR TITLE
Copy over changes from mwaterw-connect-rock-library

### PR DESCRIPTION
**Pull request by waterwo2**
Pulled in code from mwaterw-field-functionality-2 to help.
CLOSE THAT ONE FIRST #18.

Added code to send request to rock-library server and get a valid response.

Jira Story: https://tim-kaufenberg.atlassian.net/browse/ARC-102

### CODE REVIEW

**Comment by waterwo2** [comment]
CLOSE OTHER ONE FIRST #18.

**Review by skitscha — COMMENTED** [review]
Can we selectively port the rock library request changes over from this branch instead of porting all of the changes from this branch? I'm pretty sure this may break arc-ui if we check this in.

**Comment by waterwo2** [comment]
I believe we just have to merge the other branch into arc-ui first, then the only "new" changes will be the connect-rock-library changes. I also only pulled in the changes from the new mwaterw-functionality branch instead of all the old stuff.

**Comment by waterwo2** [comment]
My bad. Somehow it was getting merged into master which is def not what we want. Updated to push to arc-ui, that may resolve some conflicts.

**Comment by skitscha** [comment]
image
There is a syntax error with this code. This error needs to be addressed before it can be merged.

**Comment by waterwo2** [comment]
The syntax error is not relevant, it still runs and works. It cannot be modified. I hope that is okay. Also I just merged in arc-ui after the other pull request closed (#18).

**Review by skitscha — APPROVED** [review]

**Review by mattshoobs — APPROVED** [review]

**Pull request merged**
